// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Request struct {
	ID                  string
	Kind                int64
	Datetime            time.Time
	Host                string
	Clientip            string
	Clientauthorization string
	Clientprocessname   sql.NullString
	Requestmethod       sql.NullString
	Requesturl          sql.NullString
	Requestheaders      []byte
	Requestbody         []byte
	Responsestatus      sql.NullInt64
	Responseheaders     []byte
	Responsebody        []byte
	Error               sql.NullString
}
